/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedMemoryMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abandonGame"
      | "activeGames"
      | "flipCard"
      | "getGameState"
      | "getLeaderboard"
      | "getPlayerRank"
      | "getPlayerStats"
      | "leaderboard"
      | "playerStats"
      | "protocolId"
      | "resetGame"
      | "resolveMatch"
      | "startGame"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CardFlipped"
      | "CardsMatched"
      | "CardsNotMatched"
      | "GameEnded"
      | "GameStarted"
      | "LeaderboardUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "abandonGame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeGames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flipCard",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRank",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resetGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveMatch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "startGame", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "abandonGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flipCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startGame", data: BytesLike): Result;
}

export namespace CardFlippedEvent {
  export type InputTuple = [
    player: AddressLike,
    cardIndex: BigNumberish,
    cardValue: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    cardIndex: bigint,
    cardValue: bigint
  ];
  export interface OutputObject {
    player: string;
    cardIndex: bigint;
    cardValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardsMatchedEvent {
  export type InputTuple = [
    player: AddressLike,
    card1Index: BigNumberish,
    card2Index: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    card1Index: bigint,
    card2Index: bigint
  ];
  export interface OutputObject {
    player: string;
    card1Index: bigint;
    card2Index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardsNotMatchedEvent {
  export type InputTuple = [
    player: AddressLike,
    card1Index: BigNumberish,
    card2Index: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    card1Index: bigint,
    card2Index: bigint
  ];
  export interface OutputObject {
    player: string;
    card1Index: bigint;
    card2Index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameEndedEvent {
  export type InputTuple = [
    player: AddressLike,
    won: boolean,
    finalScore: BigNumberish
  ];
  export type OutputTuple = [player: string, won: boolean, finalScore: bigint];
  export interface OutputObject {
    player: string;
    won: boolean;
    finalScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [player: AddressLike, sessionId: BigNumberish];
  export type OutputTuple = [player: string, sessionId: bigint];
  export interface OutputObject {
    player: string;
    sessionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [player: AddressLike, newRank: BigNumberish];
  export type OutputTuple = [player: string, newRank: bigint];
  export interface OutputObject {
    player: string;
    newRank: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedMemoryMatch extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedMemoryMatch;
  waitForDeployment(): Promise<this>;

  interface: EncryptedMemoryMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abandonGame: TypedContractMethod<[], [void], "nonpayable">;

  activeGames: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        player: string;
        sessionId: bigint;
        flippedCard1: bigint;
        flippedCard2: bigint;
        steps: bigint;
        score: bigint;
        matchedPairs: bigint;
        gameEnded: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;

  flipCard: TypedContractMethod<
    [cardIndex: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getGameState: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint[],
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        sessionId: bigint;
        board: bigint[];
        flippedCard1: bigint;
        flippedCard2: bigint;
        steps: bigint;
        score: bigint;
        matchedPairs: bigint;
        gameEnded: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [],
    [
      [string[], bigint[], bigint[]] & {
        players: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getPlayerRank: TypedContractMethod<
    [],
    [[bigint, bigint] & { rank: bigint; score: bigint }],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        gamesPlayed: bigint;
        gamesWon: bigint;
        bestScore: bigint;
      }
    ],
    "view"
  >;

  leaderboard: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        player: string;
        score: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        gamesPlayed: bigint;
        gamesWon: bigint;
        bestScore: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  resetGame: TypedContractMethod<[], [void], "nonpayable">;

  resolveMatch: TypedContractMethod<[], [void], "nonpayable">;

  startGame: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abandonGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeGames"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        player: string;
        sessionId: bigint;
        flippedCard1: bigint;
        flippedCard2: bigint;
        steps: bigint;
        score: bigint;
        matchedPairs: bigint;
        gameEnded: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "flipCard"
  ): TypedContractMethod<
    [cardIndex: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGameState"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint[],
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        sessionId: bigint;
        board: bigint[];
        flippedCard1: bigint;
        flippedCard2: bigint;
        steps: bigint;
        score: bigint;
        matchedPairs: bigint;
        gameEnded: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [],
    [
      [string[], bigint[], bigint[]] & {
        players: string[];
        scores: bigint[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerRank"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rank: bigint; score: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        gamesPlayed: bigint;
        gamesWon: bigint;
        bestScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        player: string;
        score: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        gamesPlayed: bigint;
        gamesWon: bigint;
        bestScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resetGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMatch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGame"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CardFlipped"
  ): TypedContractEvent<
    CardFlippedEvent.InputTuple,
    CardFlippedEvent.OutputTuple,
    CardFlippedEvent.OutputObject
  >;
  getEvent(
    key: "CardsMatched"
  ): TypedContractEvent<
    CardsMatchedEvent.InputTuple,
    CardsMatchedEvent.OutputTuple,
    CardsMatchedEvent.OutputObject
  >;
  getEvent(
    key: "CardsNotMatched"
  ): TypedContractEvent<
    CardsNotMatchedEvent.InputTuple,
    CardsNotMatchedEvent.OutputTuple,
    CardsNotMatchedEvent.OutputObject
  >;
  getEvent(
    key: "GameEnded"
  ): TypedContractEvent<
    GameEndedEvent.InputTuple,
    GameEndedEvent.OutputTuple,
    GameEndedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;

  filters: {
    "CardFlipped(address,uint8,uint8)": TypedContractEvent<
      CardFlippedEvent.InputTuple,
      CardFlippedEvent.OutputTuple,
      CardFlippedEvent.OutputObject
    >;
    CardFlipped: TypedContractEvent<
      CardFlippedEvent.InputTuple,
      CardFlippedEvent.OutputTuple,
      CardFlippedEvent.OutputObject
    >;

    "CardsMatched(address,uint8,uint8)": TypedContractEvent<
      CardsMatchedEvent.InputTuple,
      CardsMatchedEvent.OutputTuple,
      CardsMatchedEvent.OutputObject
    >;
    CardsMatched: TypedContractEvent<
      CardsMatchedEvent.InputTuple,
      CardsMatchedEvent.OutputTuple,
      CardsMatchedEvent.OutputObject
    >;

    "CardsNotMatched(address,uint8,uint8)": TypedContractEvent<
      CardsNotMatchedEvent.InputTuple,
      CardsNotMatchedEvent.OutputTuple,
      CardsNotMatchedEvent.OutputObject
    >;
    CardsNotMatched: TypedContractEvent<
      CardsNotMatchedEvent.InputTuple,
      CardsNotMatchedEvent.OutputTuple,
      CardsNotMatchedEvent.OutputObject
    >;

    "GameEnded(address,bool,uint32)": TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;
    GameEnded: TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;

    "GameStarted(address,uint256)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "LeaderboardUpdated(address,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
  };
}
